/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const InviteStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const InviteRequest = IDL.Record({
  'status' : InviteStatus,
  'linkedin' : IDL.Text,
  'requestId' : IDL.Nat,
  'source' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'assignedManagerId' : IDL.Opt(IDL.Nat),
  'timestamp' : IDL.Int,
  'phone' : IDL.Text,
});
export const Manager = IDL.Record({
  'id' : IDL.Nat,
  'bio' : IDL.Opt(IDL.Text),
  'contactInfo' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
});
export const Time = IDL.Int;
export const RSVP = IDL.Record({
  'name' : IDL.Text,
  'inviteCode' : IDL.Text,
  'timestamp' : Time,
  'attending' : IDL.Bool,
});
export const InviteCode = IDL.Record({
  'created' : Time,
  'code' : IDL.Text,
  'used' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addManager' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'approveInvite' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkInviteStatus' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(InviteRequest)],
      ['query'],
    ),
  'generateInviteCode' : IDL.Func([], [IDL.Text], []),
  'getAllInviteRequests' : IDL.Func([], [IDL.Vec(InviteRequest)], ['query']),
  'getAllManagers' : IDL.Func([], [IDL.Vec(Manager)], ['query']),
  'getAllRSVPs' : IDL.Func([], [IDL.Vec(RSVP)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getInviteCodes' : IDL.Func([], [IDL.Vec(InviteCode)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'rejectInvite' : IDL.Func([IDL.Nat], [], []),
  'removeManager' : IDL.Func([IDL.Nat], [], []),
  'submitInviteRequest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'submitRSVP' : IDL.Func([IDL.Text, IDL.Bool, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const InviteStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const InviteRequest = IDL.Record({
    'status' : InviteStatus,
    'linkedin' : IDL.Text,
    'requestId' : IDL.Nat,
    'source' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'assignedManagerId' : IDL.Opt(IDL.Nat),
    'timestamp' : IDL.Int,
    'phone' : IDL.Text,
  });
  const Manager = IDL.Record({
    'id' : IDL.Nat,
    'bio' : IDL.Opt(IDL.Text),
    'contactInfo' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
  });
  const Time = IDL.Int;
  const RSVP = IDL.Record({
    'name' : IDL.Text,
    'inviteCode' : IDL.Text,
    'timestamp' : Time,
    'attending' : IDL.Bool,
  });
  const InviteCode = IDL.Record({
    'created' : Time,
    'code' : IDL.Text,
    'used' : IDL.Bool,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addManager' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'approveInvite' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkInviteStatus' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(InviteRequest)],
        ['query'],
      ),
    'generateInviteCode' : IDL.Func([], [IDL.Text], []),
    'getAllInviteRequests' : IDL.Func([], [IDL.Vec(InviteRequest)], ['query']),
    'getAllManagers' : IDL.Func([], [IDL.Vec(Manager)], ['query']),
    'getAllRSVPs' : IDL.Func([], [IDL.Vec(RSVP)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getInviteCodes' : IDL.Func([], [IDL.Vec(InviteCode)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'rejectInvite' : IDL.Func([IDL.Nat], [], []),
    'removeManager' : IDL.Func([IDL.Nat], [], []),
    'submitInviteRequest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'submitRSVP' : IDL.Func([IDL.Text, IDL.Bool, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };