/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface InviteCode {
  'created' : Time,
  'code' : string,
  'used' : boolean,
}
export type InviteStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface Manager {
  'id' : bigint,
  'bio' : [] | [string],
  'contactInfo' : [] | [string],
  'name' : string,
}
export type ManagerId = bigint;
export type Occupation = { 'ceoOrExecutive' : null } |
  { 'entrepreneurBusinessOwner' : null } |
  { 'partnerOrDirector' : null } |
  { 'lawProfessional' : null } |
  { 'medicalProfessional' : null } |
  { 'notListed' : null } |
  { 'pilot' : null } |
  { 'corporateProfessional' : null };
export type PreferredCallTime = { 'morning' : null } |
  { 'evening' : null } |
  { 'afternoon' : null };
export type PremiumIncomeRange = { 'range50kTo75k' : null } |
  { 'range25kTo50k' : null } |
  { 'range75kTo100k' : null } |
  { 'range100kPlus' : null };
export interface PremiumQualification {
  'id' : bigint,
  'occupation' : Occupation,
  'status' : InviteStatus,
  'linkedin' : string,
  'preferredCallTime' : PreferredCallTime,
  'annualPremiumRange' : PremiumIncomeRange,
  'name' : string,
  'email' : string,
  'referredBy' : [] | [string],
  'timestamp' : bigint,
  'totalHealthCover' : [] | [bigint],
  'phone' : string,
}
export type PremiumQualificationId = bigint;
export interface RSVP {
  'name' : string,
  'inviteCode' : string,
  'timestamp' : Time,
  'attending' : boolean,
}
export type Time = bigint;
export interface UserProfile { 'name' : string, 'email' : [] | [string] }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addManager' : ActorMethod<[string, [] | [string], [] | [string]], ManagerId>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkQualificationStatus' : ActorMethod<
    [string],
    [] | [PremiumQualification]
  >,
  'generateInviteCode' : ActorMethod<[], string>,
  'getAllManagers' : ActorMethod<[], Array<Manager>>,
  'getAllQualifications' : ActorMethod<[], Array<PremiumQualification>>,
  'getAllRSVPs' : ActorMethod<[], Array<RSVP>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getInviteCodes' : ActorMethod<[], Array<InviteCode>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeManager' : ActorMethod<[ManagerId], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitQualification' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      [] | [string],
      [] | [bigint],
      PremiumIncomeRange,
      Occupation,
      PreferredCallTime,
    ],
    PremiumQualificationId
  >,
  'submitRSVP' : ActorMethod<[string, boolean, string], undefined>,
  'updateQualificationStatus' : ActorMethod<
    [PremiumQualificationId, InviteStatus],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];