/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface InviteCode {
  'created' : Time,
  'code' : string,
  'used' : boolean,
}
export interface InviteRequest {
  'status' : InviteStatus,
  'linkedin' : string,
  'requestId' : bigint,
  'source' : string,
  'name' : string,
  'email' : string,
  'assignedManagerId' : [] | [bigint],
  'timestamp' : bigint,
  'phone' : string,
}
export type InviteStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface Manager {
  'id' : bigint,
  'bio' : [] | [string],
  'contactInfo' : [] | [string],
  'name' : string,
}
export interface RSVP {
  'name' : string,
  'inviteCode' : string,
  'timestamp' : Time,
  'attending' : boolean,
}
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addManager' : ActorMethod<[string, [] | [string], [] | [string]], bigint>,
  'approveInvite' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkInviteStatus' : ActorMethod<[string], [] | [InviteRequest]>,
  'generateInviteCode' : ActorMethod<[], string>,
  'getAllInviteRequests' : ActorMethod<[], Array<InviteRequest>>,
  'getAllManagers' : ActorMethod<[], Array<Manager>>,
  'getAllRSVPs' : ActorMethod<[], Array<RSVP>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getInviteCodes' : ActorMethod<[], Array<InviteCode>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'rejectInvite' : ActorMethod<[bigint], undefined>,
  'removeManager' : ActorMethod<[bigint], undefined>,
  'submitInviteRequest' : ActorMethod<
    [string, string, string, string, string],
    bigint
  >,
  'submitRSVP' : ActorMethod<[string, boolean, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];